[build]
builder = "DOCKERFILE"
watchPatterns = [
    "api/package.json",
    "api/src/**",
    "client/package.json",
    "client/src/**",
    "railway.toml",
    "api/Dockerfile",
    "client/Dockerfile"
]

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[api]
builder = "DOCKERFILE"
dockerfilePath = "./api/Dockerfile"

[client]
builder = "DOCKERFILE"
dockerfilePath = "./client/Dockerfile"