[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "api/package.json",
    "api/src/**",
    "client/package.json",
    "client/src/**",
    "railway.toml",
    "api/Dockerfile",
    "client/Dockerfile",
    "docker-compose.yml"
]

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10